### ISSUE TITLE
The hyperlinks in the PyPI readme text are misformed

### ISSUE THREAD

**Issue by DanielSank** [google/duet#12]
See [here](https://pypi.org/project/duet-async/).

**Comment by DanielSank** [comment]
Also the section headings are rendering strangely.

**Comment by A5rocks** [comment]
I believe the reason for this is that PyPI defaults to ReStructuredText, whereas the README is markdown.

Perhaps pass `long_description_content_type="text/markdown"` into `setuptools.setup`?
