### ISSUE TITLE
Add support for python 3.6

### ISSUE THREAD

**Issue by maffoo** [google/duet#22]
We'd like to be able to use duet in python3.6 since it's still used by colab and internally at google (see https://github.com/quantumlib/Cirq/pull/4009). Among other things, this will require adding back in support for AsyncContextManager and adding a 3.6-only dependency on [contextvars](https://pypi.org/project/contextvars/). There may be some other changes required as well.

**Comment by fedimser** [comment]
I found other thing which duet uses and which is not available in Python 3.6: postponed evalutaion of annotations ([PEP 563](https://www.python.org/dev/peps/pep-0563/)). This was added in Python 3.7, so in Python 3.6 statement `from __future__ import annotations` result in an error.

I am thinking about dropping this, i.e. removing all `from __future__ import annotations` lines. If I understand correctly how typing works, we just will have to quote type annotations in few places.
